In [1]:
import pandas as pd
import requests
import json
import re
from tqdm import tqdm
import os
import pandas as pd
import time
import math
from glob import glob
import uuid

import pyarrow.feather as feather
from tqdm import tqdm
from scipy.stats import rankdata, zscore

In [2]:
sn = "Homo_sapiens"
organism = "Mammalia/%s"%sn
url = 'ftp://ftp.ncbi.nih.gov/gene/DATA/GENE_INFO/{}.gene_info.gz'.format(organism)
file = '{}.gene_info.tsv'.format(organism)

In [3]:
def fetch_save_read(url, file, reader=pd.read_csv, sep='\t', **kwargs):
  ''' Download file from {url}, save it to {file}, and subsequently read it with {reader} using pandas options on {**kwargs}.
  '''
  if not os.path.exists(file):
    if os.path.dirname(file):
      os.makedirs(os.path.dirname(file), exist_ok=True)
    df = reader(url, sep=sep, index_col=None)
    df.to_csv(file, sep=sep, index=False)
  return pd.read_csv(file, sep=sep, **kwargs)

In [4]:
ncbi_gene = fetch_save_read(url, file)
ncbi_gene.head()

,#tax_id,GeneID,Symbol,LocusTag,Synonyms,dbXrefs,chromosome,map_location,description,type_of_gene,Symbol_from_nomenclature_authority,Full_name_from_nomenclature_authority,Nomenclature_status,Other_designations,Modification_date,Feature_type
0,9606,1,A1BG,-,A1B|ABG|GAB|HYST2477,MIM:138670|HGNC:HGNC:5|Ensembl:ENSG00000121410...,19,19q13.43,alpha-1-B glycoprotein,protein-coding,A1BG,alpha-1-B glycoprotein,O,alpha-1B-glycoprotein|HEL-S-163pA|epididymis s...,20231010,-
1,9606,2,A2M,-,A2MD|CPAMD5|FWP007|S863-7,MIM:103950|HGNC:HGNC:7|Ensembl:ENSG00000175899...,12,12p13.31,alpha-2-macroglobulin,protein-coding,A2M,alpha-2-macroglobulin,O,alpha-2-macroglobulin|C3 and PZP-like alpha-2-...,20231010,-
2,9606,3,A2MP1,-,A2MP,HGNC:HGNC:8|Ensembl:ENSG00000291190|AllianceGe...,12,12p13.31,alpha-2-macroglobulin pseudogene 1,pseudo,A2MP1,alpha-2-macroglobulin pseudogene 1,O,pregnancy-zone protein pseudogene,20231010,-
3,9606,9,NAT1,-,AAC1|MNAT|NAT-1|NATI,MIM:108345|HGNC:HGNC:7645|Ensembl:ENSG00000171...,8,8p22,N-acetyltransferase 1,protein-coding,NAT1,N-acetyltransferase 1,O,arylamine N-acetyltransferase 1|N-acetyltransf...,20231010,-
4,9606,10,NAT2,-,AAC2|NAT-2|PNAT,MIM:612182|HGNC:HGNC:7646|Ensembl:ENSG00000156...,8,8p22,N-acetyltransferase 2,protein-coding,NAT2,N-acetyltransferase 2,O,arylamine N-acetyltransferase 2|N-acetyltransf...,20231010,-

In [5]:
def maybe_split(record):
    ''' NCBI Stores Nulls as '-' and lists '|' delimited
    '''
    if record in {'', '-'}:
        return set()
    return set(record.split('|'))

def supplement_dbXref_prefix_omitted(ids):
    ''' NCBI Stores external IDS with Foreign:ID while most datasets just use the ID
    '''
    for id in ids:
        # add original id
        yield id
        # also add id *without* prefix
        if ':' in id:
            yield id.split(':', maxsplit=1)[1]

ncbi_gene['All_synonyms'] = [
    set.union(
      maybe_split(gene_info['Symbol']),
      maybe_split(gene_info['Symbol_from_nomenclature_authority']),
      maybe_split(str(gene_info['GeneID'])),
      maybe_split(gene_info['Synonyms']),
      maybe_split(gene_info['Other_designations']),
      maybe_split(gene_info['LocusTag']),
      set(supplement_dbXref_prefix_omitted(maybe_split(gene_info['dbXrefs']))),
    )
    for _, gene_info in ncbi_gene.iterrows()
  ]

ncbi_gene['All_synonyms'] = [
    set.union(
      maybe_split(gene_info['Symbol']),
      maybe_split(gene_info['Symbol_from_nomenclature_authority']),
      maybe_split(str(gene_info['GeneID'])),
      maybe_split(gene_info['Synonyms']),
      maybe_split(gene_info['Other_designations']),
      maybe_split(gene_info['LocusTag']),
      set(supplement_dbXref_prefix_omitted(maybe_split(gene_info['dbXrefs']))),
    )
    for _, gene_info in ncbi_gene.iterrows()
  ]

synonyms, gene_id = zip(*{
    (synonym, gene_info['Symbol'])
    for _, gene_info in ncbi_gene.iterrows()
    for synonym in gene_info['All_synonyms']
  })
ncbi_lookup_syn = pd.Series(gene_id, index=synonyms)
symbols, cap, gene_id = zip(*{
    (gene_info['Symbol'], gene_info['Symbol'].upper(), gene_info['Symbol'])
    for _, gene_info in ncbi_gene.iterrows()
  })
ncbi_lookup_sym = pd.Series(gene_id, index=symbols)
ncbi_lookup_sym_cap = pd.Series(gene_id, index=cap)

index_values = ncbi_lookup_syn.index.value_counts()
ambiguous = index_values[index_values > 1].index
ncbi_lookup_syn_disambiguated = ncbi_lookup_syn[(
(ncbi_lookup_syn.index == ncbi_lookup_syn) | (~ncbi_lookup_syn.index.isin(ambiguous))
)]
all_genes = {}
ncbi_lookup_sym = ncbi_lookup_sym.to_dict()
ncbi_lookup_sym_cap = ncbi_lookup_sym_cap.to_dict()
ncbi_lookup_syn_disambiguated = ncbi_lookup_syn_disambiguated.to_dict()
def gene_lookup(gene):
    gene_id = ncbi_lookup_sym.get(gene)
    if gene_id: return str(gene_id)
    gene_id = ncbi_lookup_sym_cap.get(gene)
    if gene_id: return str(gene_id)
    return str(ncbi_lookup_syn_disambiguated.get(gene))

In [6]:
df = pd.read_csv('data/gwas_catalog_v1.0-associations_e114_r2025-07-21.tsv', sep="\t")
df.head()

/var/folders/wq/7bkxhy8j7ql194c1fbby4gy40000gn/T/ipykernel_99908/885465135.py:1: DtypeWarning: Columns (9,11,12,13,23,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/gwas_catalog_v1.0-associations_e114_r2025-07-21.tsv', sep="\t")

,DATE ADDED TO CATALOG,PUBMEDID,FIRST AUTHOR,DATE,JOURNAL,LINK,STUDY,DISEASE/TRAIT,INITIAL SAMPLE SIZE,REPLICATION SAMPLE SIZE,...,CONTEXT,INTERGENIC,RISK ALLELE FREQUENCY,P-VALUE,PVALUE_MLOG,P-VALUE (TEXT),OR or BETA,95% CI (TEXT),PLATFORM [SNPS PASSING QC],CNV
0,2018-07-24,26426971,Winkler TW,2015-10-01,PLoS Genet,www.ncbi.nlm.nih.gov/pubmed/26426971,The Influence of Age and Sex on Genetic Associ...,Body mass index,"up to 309,889 European ancestry individuals",NaN,...,intron_variant,0.0,0.443345967509007,8.000000e-11,10.09691,NaN,0.017530,unit decrease,"Affymetrix, Illumina, Perlegen [up to 2800000]...",N
1,2018-07-24,26426971,Winkler TW,2015-10-01,PLoS Genet,www.ncbi.nlm.nih.gov/pubmed/26426971,The Influence of Age and Sex on Genetic Associ...,Body mass index,"up to 309,889 European ancestry individuals",NaN,...,intergenic_variant,1.0,0.828391384341878,1.000000e-74,74.00000,NaN,0.065630,unit increase,"Affymetrix, Illumina, Perlegen [up to 2800000]...",N
2,2018-07-24,26426971,Winkler TW,2015-10-01,PLoS Genet,www.ncbi.nlm.nih.gov/pubmed/26426971,The Influence of Age and Sex on Genetic Associ...,Body mass index,"up to 309,889 European ancestry individuals",NaN,...,intron_variant,1.0,0.538102907902883,2.000000e-30,29.69897,NaN,0.031007,unit decrease,"Affymetrix, Illumina, Perlegen [up to 2800000]...",N
3,2018-07-24,26426971,Winkler TW,2015-10-01,PLoS Genet,www.ncbi.nlm.nih.gov/pubmed/26426971,The Influence of Age and Sex on Genetic Associ...,Body mass index,"up to 309,889 European ancestry individuals",NaN,...,3_prime_UTR_variant,0.0,0.476391319841233,2.000000e-09,8.69897,NaN,0.015954,unit increase,"Affymetrix, Illumina, Perlegen [up to 2800000]...",N
4,2018-07-24,26426971,Winkler TW,2015-10-01,PLoS Genet,www.ncbi.nlm.nih.gov/pubmed/26426971,The Influence of Age and Sex on Genetic Associ...,Body mass index,"up to 309,889 European ancestry individuals",NaN,...,intron_variant,0.0,0.393092979831593,1.000000e-14,14.00000,NaN,0.021147,unit decrease,"Affymetrix, Illumina, Perlegen [up to 2800000]...",N

In [7]:
cols = ['DISEASE/TRAIT', 
       'REPORTED GENE(S)', 'MAPPED_GENE', 'UPSTREAM_GENE_ID',
       'DOWNSTREAM_GENE_ID',  'SNP_GENE_IDS',  'P-VALUE', 'PVALUE_MLOG', 'P-VALUE (TEXT)',
       ]

df = df[cols]

In [8]:
df.head()

,DISEASE/TRAIT,REPORTED GENE(S),MAPPED_GENE,UPSTREAM_GENE_ID,DOWNSTREAM_GENE_ID,SNP_GENE_IDS,P-VALUE,PVALUE_MLOG,P-VALUE (TEXT)
0,Body mass index,NR,"IPO9-AS1, NAV1",NaN,NaN,"ENSG00000231871, ENSG00000134369",8.000000e-11,10.09691,NaN
1,Body mass index,NR,LINC01875 - TMEM18,ENSG00000225942,ENSG00000151353,NaN,1.000000e-74,74.00000,NaN
2,Body mass index,NR,ADCY3 - DNAJC27,ENSG00000138031,ENSG00000115137,NaN,2.000000e-30,29.69897,NaN
3,Body mass index,NR,KCNK3,NaN,NaN,ENSG00000171303,2.000000e-09,8.69897,NaN
4,Body mass index,NR,LINC01122,NaN,NaN,ENSG00000233723,1.000000e-14,14.00000,NaN

In [9]:
len(set(df['DISEASE/TRAIT']))

43603

In [10]:
all_genes = {}
for genes in tqdm(df['REPORTED GENE(S)'].unique()):
    if type(genes) == str:
        for g1 in genes.split(","):
            for g in g1.split("|"):    
                gene = g.strip()
                if gene not in all_genes:
                    all_genes[gene] = ''

100%|██████████| 32399/32399 [00:00<00:00, 1084267.58it/s]

In [11]:
len(all_genes)

27270

In [12]:
for gene in tqdm(all_genes):
    all_genes[gene] = gene_lookup(gene)

100%|██████████| 27270/27270 [00:00<00:00, 625187.46it/s]

In [13]:
with open("out/all_genes.json", 'w') as o:
    o.write(json.dumps(all_genes))

In [14]:
gmt = {}
none_counter = {}
for i, row in tqdm(df.iterrows()):
    disease = row['DISEASE/TRAIT']
    if disease not in gmt:
        gmt[disease] = set()
    genes = row["REPORTED GENE(S)"]
    if type(genes) == str:
        for g1 in genes.split(","):
            for g in g1.split("|"):
                gene = all_genes[g.strip()]
                if gene != 'None':
                    gmt[disease].add(gene)
                else:
                    if g.strip() not in none_counter:
                        none_counter[g.strip()] = 0
                    none_counter[g.strip()] += 1

938544it [00:15, 60863.52it/s]

In [15]:
len(none_counter)

6341

In [16]:
len(gmt)

43603

In [17]:
list(gmt.keys())[0]

'Body mass index'

In [20]:
new_gmt = {}
for k, v in gmt.items():
	if len(v) > 5:
		new_gmt[k] = v

In [17]:
import csv

In [31]:
with open('out/GWAS_Catalog_2025.gmt', 'w') as o:
    for k,v in gmt.items():
        if len(v) >= 5:
            row = [k, ''] + list(v)
            o.write("\t".join(row) + "\n")